// lib/models/EmergencyContact.g.dart
// NOTE: This file is auto-generated by build_runner.
// Run: flutter pub run build_runner build --delete-conflicting-outputs
// 
// If you are not using Hive code generation, you can skip the @HiveType/@HiveField
// annotations and use the manual adapter below instead.
//
// MANUAL ADAPTER (use this if you don't want to run build_runner):
// Register in main.dart with: Hive.registerAdapter(EmergencyContactAdapter());

part of 'EmergencyContact.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class EmergencyContactAdapter extends TypeAdapter<EmergencyContact> {
  @override
  final int typeId = 0;

  @override
  EmergencyContact read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return EmergencyContact(
      name: fields[0] as String,
      phone: fields[1] as String,
      relation: fields[2] as String,
      isPrimary: fields[3] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, EmergencyContact obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.name)
      ..writeByte(1)
      ..write(obj.phone)
      ..writeByte(2)
      ..write(obj.relation)
      ..writeByte(3)
      ..write(obj.isPrimary);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmergencyContactAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}